### ISSUE TITLE
Allow passing arbitrary environment variables through to gordo-deploy job

### ISSUE THREAD

**Issue by milesgranger** [equinor/gordo-controller#26]
Problem :peanuts: 
---
`gordo-components workflow generate` takes a number of arguments such as `--docker-repository` and `--docker-registry`. But there is no way to pass these parameters to the gordo-deploy job itself.

Solution? :kiwi_fruit: 
---
Add another (optional) field to the CRD spec to define `gordo-deploy-environment`

ie. 
```yaml
spec:
  gordo-deploy: latest
  gordo-deploy-environment:
    DOCKER_REGISTRY: equinor
  ...
```
Or maybe these should all be combined under the same `gordo-deploy` key?

Anyhow, these `environment` variables can then be passed into the gordo-deploy job the controller launches.
